version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: dermcare-https-proxy
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
