version: '3'

services:
  be_boilerplate:
    deploy:
      resources:
        limits:
          cpus: '0.90'
          # memory: 400M
    build:
      dockerfile: Dockerfile.prod
    ports:
      - '4000:4000'
    env_file:
      - ./.env

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: dermcare_cloudflare_tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiOGY2OTdkMmVhYmE3Y2Y4MTYxYTNkNDhiYjZlNGNkMTciLCJ0IjoiZTI3NTRjZDEtNDMwOS00OTUxLWI4ZWYtNDNkYjgzMzI3YzA2IiwicyI6IlpHSTVaakppWTJNdE9EWTJZaTAwTVRBNUxUbGlaRFF0WkRrMU5ESmhNemxpTjJNdyJ9
    depends_on:
      - be_boilerplate
